spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/primary

logging.level:
  org.springframework.data.mongodb.core.MongoTemplate: DEBUG
  org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG